version: "3.8"

networks:
  backend:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - redis
    restart: always
  api:
    image: pda/research-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research-server
    networks:
      - backend
    depends_on:
      - maria
      - redis
    restart: always
  maria:
    image: docker.io/bitnami/mariadb:10.6
    container_name: re_search_mariadb
    expose:
      - "3306"
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=re_search
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
    networks:
      - backend
    restart: always
  redis:
    image: redis:7.2.4
    container_name: re_search_redis
    expose:
      - "6379"
    command: redis-server --port 6379
    volumes:
      - ~/docker/redis/data:/data
      - ~/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend
    restart: always

